name: "E2E NuvlaBox Testing"

on:
  push:
    branches:
      - e2e

jobs:
  tagged-release:
    name: "Run NuvlaBox E2E testing"
    runs-on: "ubuntu-latest"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test with pytest
        env:
          NUVLA_DEV_APIKEY: ${{ secrets.NUVLA_DEV_APIKEY }}
          NUVLA_DEV_APISECRET: ${{ secrets.NUVLA_DEV_APISECRET }}
          SNYK_SIXSQCI_API_TOKEN: ${{ secrets.SNYK_SIXSQCI_API_TOKEN }}
        run: |
          apt-get install -y python-pytest
          cd test
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install snyk
          pytest --remote --cis -vv -x --html=nuvlabox.e2e_pytest.output.html --self-contained-html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: test/nuvlabox.e2e_pytest.output.html

      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: test/nuvlabox.e2e_pytest.output.html
          channel: travis-ci
          initial_comment: "NuvlaBox E2E PyTest report :wrench:"


  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - tagged-release
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':wrench:'